name: Tests
on: push

jobs:
  test:
    name: Compile and run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "1.15"
      - run: go build -o test.bin ./test/
      - run: test/test.sh
